using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Audio;
using UnityEngine.UI;
using TMPro;
using System.Linq;
using Player;

public class OptionsMenu : MonoBehaviour
{
    [SerializeField] TMP_Dropdown resolutionDropdown, graphicsDropdown;
    [SerializeField] Toggle fullscreenToggle;
    [SerializeField] Slider sensitivitySlider;

    Resolution currentResolution;
    Resolution[] resolutions;

    void Start()
    {
        currentResolution = Screen.currentResolution;
        InitResolutions();
        InitQuality();
        InitFullscreen();
        InitSensitivity();
    }

    void Update()
    {
        
    }

    public void SetResolution(int resolutionIndex)
    {
        Resolution resolution = resolutions[resolutionIndex];
        Screen.SetResolution(resolution.width, resolution.height, Screen.fullScreenMode);
        currentResolution = resolution;
    }

    public void ToggleFullscreen(bool isFullscreen)
    {
        fullscreenToggle.isOn = isFullscreen;
        Screen.fullScreenMode = isFullscreen ? FullScreenMode.MaximizedWindow : FullScreenMode.Windowed;
        Screen.fullScreen = isFullscreen;
        Screen.SetResolution(currentResolution.width, currentResolution.height, isFullscreen);
    }

    public void SetQuality(int quality)
    {
        QualitySettings.SetQualityLevel(quality);
    }

    void InitFullscreen()
    {
        fullscreenToggle.isOn = Screen.fullScreen;
    }

    void InitQuality()
    {
        graphicsDropdown.ClearOptions();
        graphicsDropdown.AddOptions(QualitySettings.names.ToList());
        graphicsDropdown.value = QualitySettings.GetQualityLevel();
        graphicsDropdown.RefreshShownValue();
    }
    
    void InitResolutions()
    {
        resolutions = Screen.resolutions;
        resolutionDropdown.ClearOptions();

        List<string> options = new List<string>();
        int currentResolutionIndex = 0;
        for (int i = 0; i < resolutions.Length; i++)
        {
            string option = resolutions[i].width + "x" + resolutions[i].height;
            options.Add(option);

            if (resolutions[i].width == Screen.currentResolution.width &&
                resolutions[i].height == Screen.currentResolution.height)
            {
                currentResolutionIndex = i;
            }
        }
        resolutionDropdown.AddOptions(options);
        resolutionDropdown.value = currentResolutionIndex;
        resolutionDropdown.RefreshShownValue();
    }

    void InitSensitivity()
    {
        if (PlayerPrefs.GetFloat("Sensitivity") == 0)
        {
            PlayerPrefs.SetFloat("Sensitivity", 1);
        }
        sensitivitySlider.value = PlayerPrefs.GetFloat("Sensitivity");
    }

    public void SetSensitivity()
    {
        PlayerPrefs.SetFloat("Sensitivity", sensitivitySlider.value);

    }
}
